import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import { MantineProvider } from '@mantine/core';

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smart Recruit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          <Navbar />
          <div className="pt-24">
            {children}
          </div>
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
