version: '3.8'

services:
  web:
    build: ./smartrecruit_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./smartrecruit_backend/:/usr/src/smartrecruit_backend/
    ports:
      - 8000:8000
    env_file: 
      - ./.env.dev