version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/usr/src/smartrecruit_backend/media/
      - static_volume:/usr/src/smartrecruit_backend/static/
  web:
    build: ./smartrecruit_backend
    command: gunicorn smartrecruit_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./smartrecruit_backend/:/usr/src/smartrecruit_backend/
      - media_volume:/usr/src/smartrecruit_backend/media/
      - static_volume:/usr/src/smartrecruit_backend/static/
    expose:
      - 8000
    env_file: 
      - ./.env.dev
    depends_on:
      - db
      - daphne
  daphne:
    build: ./smartrecruit_backend
    command: daphne --bind 0.0.0.0 -p 8002 smartrecruit_backend.asgi:application
    ports: 
      - 8002:8002
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgresuserpassword
      - POSTGRES_DB=smartrecruit

volumes: 
  postgres_data:
  media_volume:
  static_volume: