# Generated by Django 5.0.4 on 2024-05-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='match_percentage',
        ),
    ]
