# Generated by Django 5.0.4 on 2024-04-30 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_assessment', '0002_assessment_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='online_assessment.assessment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
