# Generated by Django 5.0.4 on 2024-04-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='assessment_id',
            new_name='assessment',
        ),
    ]
