# Generated by Django 5.0.4 on 2024-04-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_alter_invite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='assessment',
        ),
    ]
