# Generated by Django 5.0.4 on 2024-05-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0005_invite_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='expired',
        ),
    ]
