# Generated by Django 5.0.4 on 2024-05-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_processing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
