# Generated by Django 5.0.4 on 2024-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_user_avatar_alter_user_bio_alter_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resumes'),
        ),
    ]
