# Generated by Django 5.0.4 on 2024-05-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
